import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

function buildTryOnPrompt(productName: string, productCategory: string): string {
  const categoryPrompts: Record<string, string> = {
    eyewear: `Add stylish ${productName} sunglasses/glasses to this person's face. The glasses should be positioned naturally on their face, fitting properly on the nose bridge and ears. Make it look realistic as if they're actually wearing the glasses. Maintain the original photo quality and lighting.`,
    watch: `Add a ${productName} watch to this person's left wrist. The watch should be positioned naturally and sized appropriately for their wrist. Make it look realistic as if they're actually wearing the watch. Maintain the original photo quality and lighting.`,
    clothing: `Show this person wearing a ${productName}. The clothing should fit naturally on their body with realistic folds and draping. Maintain the original photo quality, lighting, and the person's pose.`,
  };

  return categoryPrompts[productCategory] ||
    `Add ${productName} to this person in a natural, realistic way. Maintain the original photo quality and lighting.`;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const { userImage, productId, productName, productCategory } = await req.json();

    if (!userImage || !productId) {
      return new Response(
        JSON.stringify({ error: "Missing required fields: userImage and productId" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) {
      return new Response(
        JSON.stringify({ error: "Lovable AI key not configured" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    console.log(`Processing virtual try-on for product: ${productName} (${productCategory})`);

    const prompt = buildTryOnPrompt(productName, productCategory);

    // Call Lovable AI Gateway with image generation model
    const maxRetries = 3;
    let response: Response | null = null;

    for (let attempt = 0; attempt <= maxRetries; attempt++) {
      response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${LOVABLE_API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "google/gemini-2.5-flash-image",
          messages: [
            {
              role: "user",
              content: [
                { type: "text", text: prompt },
                { type: "image_url", image_url: { url: userImage } },
              ],
            },
          ],
          modalities: ["image", "text"],
        }),
      });

      if (response.status === 429 && attempt < maxRetries) {
        const delay = Math.pow(2, attempt + 1) * 1000;
        console.log(`Rate limited (attempt ${attempt + 1}/${maxRetries + 1}), retrying in ${delay}ms...`);
        await new Promise((r) => setTimeout(r, delay));
        continue;
      }
      break;
    }

    if (!response!.ok) {
      const errorText = await response!.text();
      console.error("Lovable AI error:", response!.status, errorText);

      if (response!.status === 429) {
        return new Response(
          JSON.stringify({ error: "Rate limited. Please try again shortly.", retryAfterSeconds: 30 }),
          { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      if (response!.status === 402) {
        return new Response(
          JSON.stringify({ error: "AI usage limit reached. Please add credits to your workspace." }),
          { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      throw new Error(`AI gateway error (${response!.status}): ${errorText}`);
    }

    const data = await response!.json();

    // Extract image from Lovable AI gateway response
    const choice = data.choices?.[0];
    if (!choice) {
      throw new Error("No response from AI");
    }

    const images = choice.message?.images;
    if (!images || images.length === 0) {
      throw new Error("No image was generated by AI");
    }

    const resultImage = images[0].image_url.url;

    console.log("Virtual try-on image generated successfully via Lovable AI");
    return new Response(
      JSON.stringify({ success: true, resultImage }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Virtual try-on error:", error);

    const msg = error instanceof Error ? error.message : "Unknown error";
    const status = msg.includes("429") || msg.includes("quota") ? 429 : 500;

    return new Response(
      JSON.stringify({ error: msg }),
      { status, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
